### ISSUE TITLE
LGPL license

### ISSUE THREAD

**Issue by caarmen** [popy-dev/popy-republican-calendar#1]
Hello,

Thanks for pointing me out to this project.

While the readme says that the date conversions are no longer based on my [project](https://github.com/caarmen/french-revolutionary-calender), I still see files here with code which looks ported directly from my project, and comments included verbatim.

As long as this is included, please make your project licensed under LGPL as well.

Note, linking to my unmodified library in any project has no impact on the license of that project (the L in LGPL), however modifications of my library (or a port of my library to another language) is copyleft and should keep the original license.

Many thanks!

Carmen

**Comment by caarmen** [comment]
Btw, thanks for referencing my project! I just realized that this issue might seem rude. So, apologies if that's the case. Sometimes I can focus on technicalities more than on people 😊

**Comment by popy-dev** [comment]
> I just realized that this issue might seem rude.

It could be, If i was a normal human beings. But I bet none of us are :D

I haven't yet had the time (or will) to dig into License stuff, but I'll have to choose one indeed.

> I still see files here with code which looks ported directly from my project, and comments included verbatim.

Yep. As stated in the readme, I kept them for now as a kind of legacy/tribute. Kinda stupid, hmm ?
In the end I'll probably remove them, but I intend to keep the mentions to your work. If it's ok for you of course.

**Comment by popy-dev** [comment]
I finally choosed the MIT License, and removed the ported code :(

Feel free to get back to me if i can help you !
